spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:27054/railway
    #jdbc:postgresql://localhost:5432/jwt_security
    #postgresql://postgres:1D-gbgEgEb1GGF6Cd6F4c--1acbD*fdd@monorail.proxy.rlwy.net:27054/railway
    username: postgres
    password: 1D-gbgEgEb1GGF6Cd6F4c--1acbD*fdd
#    FddEFffB6b26-F51aF3aaEaadbb6dCFC
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
